### ISSUE TITLE
navigator.managed.getSerialNumber promise always rejected

### ISSUE THREAD

**Issue by sampolahtinen** [WICG/WebApiDevice#12]
Hi There,

This is more of a question than issue.

I have been experimenting to read Google Enterprise managed Chromebox's serial number via `navigator.managed.getSerialNumber `by following the README in this repo. However, no matter what I do (Kiosk, Guest Session, direct admin login), when navigated to PWA ,I get following error message printed in the Chrome's console.

```
Uncaught (in promise) DOMException: This API  is available only for high trusted apps.
```

What I have done so far is:
- enabled flag enable-experimental-web-platform-features
- enabled flag enable-restricted-web-apis
- Created OAuth Client ID for the PWA and added this app in `Google Admin under Security > Manage Third Party App Access`
- Force installed the PWA on organizational level

Chrome version: 91.0.4456.0 (dev channel)
Boot Mode: Developer
Additional information: Chromebox has reached AUE

I think I am missing something. What specifically the `high trusted apps` mean in this case? And how can I convert my PWA to be a high trusted app?

Furthermore, the docs mentions to test out the API in the console.

`
The easiest way to verify the attribute results is calling these APIs in the Chrome DevTools Console. Take an example, the following code snippet can be used to print the current device's serial number in the console
`

This also throws the same DOMException promise error.

**Comment by Ananubis** [comment]
Hey @sampolahtinen. Sorry for making you confusing. We keep updating the terms used in documents and codes, so sometimes they are inconsistent. In your case, 'High trusted apps' equals to 'managed applications'. You may want to follow this [paragraph](https://github.com/WICG/WebApiDevice#managed-applications) to setup a force-installed application for the regular user session by using the Google Admin Console.

You will see this application appears in the launcher of any managed devices in the same organization after login (because they have been force-installed). Then, please launch it in the browser, open the Chrome DevTools Console, and try any device attributes API again.

If it still doesn't work as expected. Would you mind sharing some screenshots with the following info?
- The value of 'WebAppInstallForceList' policy shown in the chrome://policy page.
- The DevTools console with the error messages and the current web page's URL.

Thanks!

**Comment by sampolahtinen** [comment]
Hi @Ananubis  thanks for replying so fast!

I thought so that the high trusted app possibly refers to managed applications. I had the PWA force-installed and pinned on the top organizational level. So all good there.

I did few more attempts and this time I was indeed able to read the serial number, by following these steps:
1. Having the PWA being force-installed + pinned to task bar
2. Turning on the Chromebox, and stopping auto-launch kiosk app
3. Signed in to the Chrome OS with Guest User
4. Opened Chrome and again enabled following flags:  `enable-experimental-web-platform-features` and  `enable-restricted-web-apis`
5. Reload the Chrome browser (as prompted)
6. Re-launched the PWA from Taskbar
7. I was able to successfully receive the device serial number without errors

This is a great first step. 

However, our end use case would be auto-launched Kiosk PWA. When auto-launching a PWA during start-up, I am not able to read the device serial number. Unfortunately. In this specific case, providing debug information is a bit tricky.

Is there a way to auto-launch PWA with this experimental flags marked as enabeld? Or is the WebApiDevice api not yet suitable for auto-launch kiosk apps?

**Comment by Ananubis** [comment]
Good to know you are able to get the device attributes in the guest session now. We should improve our test guide to make it more clear indeed.

Sorry. We didn't enable these APIs in the Kiosk session (no matter it is manual-launched or auto-launched) at the current dev-trial stage because there is no way to enable flags in that session. But we will start an origin trial soon (ideally in two weeks after the specification is approved and published), then you will be able to try the APIs in the Kiosk session after registering your origins in the web API origin-trial console.

**Comment by sampolahtinen** [comment]
Brilliant :) Thats is really valuable information. Thank you in a million!

Where should I follow the status of the origin trial ?

**Comment by Ananubis** [comment]
In general, we are following this [origin-trial guide](https://www.chromium.org/blink/origin-trials/running-an-origin-trial) to run a orgin trial. We will send an 'intent to experiment' email; publish a blog; update the status of [Chrome status entry](https://chromestatus.com/features/5694001745231872) to 'original-trial' for this API when everything is ready. But Personally I don't know whether there is any notification mechanism that you don't need to regularly check these entries' status.

**Comment by sampolahtinen** [comment]
That is what I shall do :) Thank you for great clarificarions!
