### ISSUE TITLE
getSerialNumber throwing DOMException in current Origin Trial

### ISSUE THREAD

**Issue by sampolahtinen** [WICG/WebApiDevice#18]
Hi,

This "issue" is more of a question than issue.

Yesterday I registered to the current Origin Trial of the WebApiDevice.

When trying to read a managed device's serial number via `navigator.managed.getSerialNumber()`, I am receiving following error:

```
DOMException: The current origin cannot use this web API because it is not allowed by DeviceAttributesAllowedForOrigins policy
```

In the read me it is guided to create a `test_policy.json` file and whitelist origins ([link](https://github.com/WICG/WebApiDevice#setting-up-test-policies)). Thought as far as I have understood the purpose of the Origin Trials is that no extra flags or configurations on the device level is needed.

_"When Chrome offers an origin trial for a feature, you can register for the trial to enable the feature for all users on your origin, without requiring them to toggle any flags or switch to an alternative build of Chrome (though they may need to upgrade)"_[link](https://developer.chrome.com/blog/origin-trials/)

How can I allow my origin to use DeviceAttributes API? Manifest.json? Google Admin?

**Comment by Ananubis** [comment]
Hey, many thanks for raising this concern to us!

For other web APIs, your understanding is 100% right. After registering specific origins in the origin-trial console, the web APIs will be accessible without enabling the `--enable-experimental-web-platform-features` feature flag. Actually you can choose either way to test the new web API.

But, the `getSerialNumber()` and other similar Device Attribute APIs are a bit different because of the data sensitivity. Even website developers enable the APIs for specific origins, we still need to make sure the device admins (owners) have already explicitly allowed these origins to access their managed devices' data (like the serial number). Otherwise this would be a huge security / privacy hole.

For Chrome OS, admins need to mark the target origins / web app as "force-installed" and grant proper permission to them. This operation can be executed on Google Admin Console. But at this moment, the `DeviceAttributesAllowedForOrigins` permission policy hasn't been exposed on Google Admin Console, so we suggest developers to use the `test_policy.json` approach to work around it during origin-trial. We will finish the missing pieces before announcing GA release. Then everything will be able to configured on Google Admin Console, no local file change is needed any longer.

**Comment by sampolahtinen** [comment]
Ah I see! Thank you for the clarification!

This explains why I was not able to find such a policy/configuration on Google Admin.
