### ISSUE TITLE
getDirectoryId() seems Google-specific

### ISSUE THREAD

**Issue by reillyeon** [WICG/WebApiDevice#5]
The documentation for this interface directly references Google documentation. It also seems like between "directory ID", "serial number" and "asset tag" there are a number of different identifiers which can be associated with the device and the specification should clarify what the role and expected semantics of each of them are.

**Comment by quisquous** [comment]
This is also something that the TAG review mentioned.

**Comment by quisquous** [comment]
This is also something that the [TAG review](https://github.com/w3ctag/design-reviews/issues/606#issuecomment-774606031) mentioned.

I was wondering about a potential solution such as making a new navigator.device.getDeviceConfiguration that could get arbitrary key/value pairs (as a parallel to getManagedConfiguration), rather than exposing each value as a separate API entry point.  In other words, you could `navigator.device.getDeviceConfiguration("directoryId")` rather than `navigator.device.getDirectoryId()`.  One criticism of this idea is that it's harder to know which entry points exist for which platforms and browsers, which might be something that's better to standardize, so long as we could have a concrete way to explain what each one would mean.

Another approach is to do something more along what is suggested in that TAG review thread, to have only a single unique device identifier, and then arguably an administrator could add some managed configuration mapping of device identifier => other device information that they require.

**Comment by nightpool** [comment]
(Note that, since I think it's my comment @quisquous, i'm not a TAG reviewer or affiliated with them, I just left a comment as an interested web developer!)

**Comment by reillyeon** [comment]
I definitely prefer a more generic `navigator.managed.getDeviceConfiguration()` method however I agree that there is value in some standardization of configuration parameters. My original complaint was more about the ones suggested by the explainer feeling Google-specific and having undefined semantics.

Concepts such as asset tags and serial numbers are relatively universal in inventory management systems and so I think there is value on standardizing them as long as they can be given sufficiently precise definitions. For example, I might define "serial number" as "A manufacturer-defined value which uniquely identifies a device." (Though this might imply that the manufacturer name should be part of the value in order to guarantee uniqueness across a heterogeneous fleet.) I would then define "asset tag" as "An administrator-defined value which uniquely identifies a device within an organization." and "directory ID" as "An inventory management system-defined value which uniquely identifies a device within an organization." 

Precisely defining these parameters may also be helpful in justifying why some would benefit from standardization.

**Comment by Ananubis** [comment]
Thanks for the detailed suggestion, @reillyeon. The related description has been rephrased according to your suggestion.

Regarding a more generic method, it changes nothing because the definition and supported platform of each configuration parameter still need be well documented. Unless we want to allow some platforms expose specific configuration parameters without official announcement, because the generic method signature can accept arbitray key in concept.
